name: OSS Audit Platform

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:

    runs-on: ubuntu-latest

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      #################################################################
      # Install SCANOSS
      #################################################################

      - name: Install SCANOSS
        run: |
          pip install scanoss

      - name: Verify SCANOSS
        run: |
          scanoss-py --version

      #################################################################
      # Generate SBOM
      #################################################################

      - name: Generate SBOM
        run: |
          mkdir -p reports

          scanoss-py scan . \
            --format cyclonedx \
            --output reports/sbom.json

      #################################################################
      # Install CryptoFinder
      #################################################################

      - name: Install Crypto Finder
        run: |
          go install github.com/scanoss/crypto-finder/cmd/crypto-finder@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install CryptoFinder
        run: |
          go install github.com/IBM/crypto-detector/cmd/crypto-detector@latest

          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Verify CryptoFinder
        run: |
          crypto-finder --version

      #################################################################
      # Generate CBOM
      #################################################################

      - name: Generate CBOM
        run: |
          REPO_NAME=$(basename "$GITHUB_REPOSITORY")
          DATE=$(date +'%Y-%m-%d')

          crypto-finder scan . \
            --format cyclonedx \
            --output reports/${DATE}_${REPO_NAME}_cbom.cdx.json

      #################################################################
      # AI Report
      #################################################################

      - name: Generate AI Report
        run: |
          python main.py

      #################################################################
      # Upload Reports
      #################################################################

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: reports/
